import { Agent, SystemMetrics, AgentStatus } from "@/types/agent";
import { getTeamMembersForAgent } from "@/lib/agentTeams";

export const INITIAL_AGENTS: Agent[] = [
  {
    id: "scout", name: "SCOUT", role: "Agente de Inteligencia", color: "#00f5ff",
    status: "idle", currentTask: "En espera para investigar mercado, web y competencia.",
    tasksCompleted: 142, tokensUsed: 2400000, uptime: "14d 6h", avatar: "SC",
    animation: "idle", isSummoned: false, position: { x: 1, y: 1 },
    teamMembers: getTeamMembersForAgent("scout"),
    activeTeamAssignments: [],
    lane: null,
    zone: "desk",
    interactionTargetId: null,
    statusDetail: null,
    log: [],
  },
  {
    id: "apex", name: "APEX", role: "Agente de Ingeniería", color: "#00ff88",
    status: "idle", currentTask: "En espera para revisar código, bugs y arquitectura.",
    tasksCompleted: 89, tokensUsed: 1800000, uptime: "7d 2h", avatar: "AX",
    animation: "idle", isSummoned: false, position: { x: 2, y: 1 },
    teamMembers: getTeamMembersForAgent("apex"),
    activeTeamAssignments: [],
    lane: null,
    zone: "desk",
    interactionTargetId: null,
    statusDetail: null,
    log: [],
  },
  {
    id: "vera", name: "VERA", role: "Agente de Análisis", color: "#ffaa00",
    status: "idle", currentTask: "En espera para leer métricas, datos y variaciones.",
    tasksCompleted: 213, tokensUsed: 3100000, uptime: "21d 4h", avatar: "VR",
    animation: "idle", isSummoned: false, position: { x: 1, y: 2 },
    teamMembers: getTeamMembersForAgent("vera"),
    activeTeamAssignments: [],
    lane: null,
    zone: "desk",
    interactionTargetId: null,
    statusDetail: null,
    log: [],
  },
  {
    id: "zion", name: "ZION", role: "Agente de Estrategia", color: "#ff4466",
    status: "idle", currentTask: "En espera para priorizar estrategia y próximos pasos.",
    tasksCompleted: 67, tokensUsed: 920000, uptime: "3d 11h", avatar: "ZN",
    animation: "idle", isSummoned: false, position: { x: 2, y: 2 },
    teamMembers: getTeamMembersForAgent("zion"),
    activeTeamAssignments: [],
    lane: null,
    zone: "desk",
    interactionTargetId: null,
    statusDetail: null,
    log: [],
  },
  {
    id: "forge", name: "FORGE", role: "Agente de Automatización", color: "#f97316",
    status: "idle", currentTask: "En espera para diseñar workflows, n8n y automatizaciones.",
    tasksCompleted: 54, tokensUsed: 980000, uptime: "5d 3h", avatar: "FG",
    animation: "idle", isSummoned: false, position: { x: 3, y: 1 },
    teamMembers: getTeamMembersForAgent("forge"),
    activeTeamAssignments: [],
    lane: null,
    zone: "desk",
    interactionTargetId: null,
    statusDetail: null,
    log: [],
  },
  {
    id: "echo", name: "ECHO", role: "Agente de Comunicaciones", color: "#22d3ee",
    status: "idle", currentTask: "En espera para redactar mensajes, emails y respuestas.",
    tasksCompleted: 38, tokensUsed: 560000, uptime: "2d 8h", avatar: "EC",
    animation: "idle", isSummoned: false, position: { x: 2, y: 3 },
    teamMembers: getTeamMembersForAgent("echo"),
    activeTeamAssignments: [],
    lane: null,
    zone: "desk",
    interactionTargetId: null,
    statusDetail: null,
    log: [],
  },
  {
    id: "vox", name: "VOX", role: "Agente de Contenido", color: "#a855f7",
    status: "idle", currentTask: "En espera para crear contenido, guiones y piezas.",
    tasksCompleted: 77, tokensUsed: 1240000, uptime: "6d 2h", avatar: "VX",
    animation: "idle", isSummoned: false, position: { x: 3, y: 2 },
    teamMembers: getTeamMembersForAgent("vox"),
    activeTeamAssignments: [],
    lane: null,
    zone: "desk",
    interactionTargetId: null,
    statusDetail: null,
    log: [],
  },
  {
    id: "aria", name: "ARIA", role: "Secretaria IA y Cerebro Principal", color: "#e2e8f0",
    status: "idle", currentTask: "Monitoreando canal de entrada y coordinando equipos.",
    tasksCompleted: 0, tokensUsed: 0, uptime: "∞", avatar: "AR",
    animation: "idle", isSummoned: false, position: { x: 0, y: 0 },
    teamMembers: getTeamMembersForAgent("aria"),
    activeTeamAssignments: [],
    lane: null,
    zone: "desk",
    interactionTargetId: null,
    statusDetail: null,
    teamLead: true,
    log: [],
  },
];

export const STATUS_CONFIG: Record<AgentStatus, { label: string; color: string; pulse: boolean }> = {
  idle:        { label: "EN ESPERA",    color: "#888",    pulse: false },
  coding:      { label: "PROGRAMANDO",  color: "#00ff88", pulse: true  },
  researching: { label: "INVESTIGANDO", color: "#00f5ff", pulse: true  },
  analyzing:   { label: "ANALIZANDO",   color: "#ffaa00", pulse: true  },
  walking:     { label: "MOVIÉNDOSE",   color: "#a78bfa", pulse: false },
  meeting:     { label: "COORDINANDO",  color: "#f472b6", pulse: true  },
  break:       { label: "PAUSA",        color: "#888",    pulse: false },
  thinking:    { label: "PENSANDO",     color: "#ff4466", pulse: true  },
  running:     { label: "EJECUTANDO",   color: "#f97316", pulse: true  },
  done:        { label: "COMPLETADO",   color: "#00ff88", pulse: false },
};

export function getInitialMetrics(): SystemMetrics {
  return { totalTasks: 0, activeTasks: 0, tokensTotal: 0, requestsPerMin: 0, uptime: "45d 3h 12m", status: "nominal" };
}
